import { z } from 'zod';
import {
  e164Phone,
  ianaTimeZone,
  isoDateTime,
  latitude,
  longitude,
  requiredName,
  setupCode,
  uuid,
} from './fields.js';

/** Named presets in the `adhan` JavaScript `CalculationMethod`. */
export const PrayerMethodSchema = z.enum([
  'MuslimWorldLeague',
  'Egyptian',
  'Karachi',
  'UmmAlQura',
  'Dubai',
  'MoonsightingCommittee',
  'NorthAmerica',
  'Kuwait',
  'Qatar',
  'Singapore',
  'Tehran',
  'Turkey',
]);
export type PrayerMethod = z.infer<typeof PrayerMethodSchema>;

export const LocaleSchema = z.enum(['ar', 'en']);

export const PrayerNameSchema = z.enum([
  'fajr',
  'sunrise',
  'dhuhr',
  'asr',
  'maghrib',
  'isha',
]);

const offsetMinutes = z.number().int().gte(-180).lte(180);

export const PrayerOffsetsSchema = z.object({
  fajr: offsetMinutes.optional(),
  sunrise: offsetMinutes.optional(),
  dhuhr: offsetMinutes.optional(),
  asr: offsetMinutes.optional(),
  maghrib: offsetMinutes.optional(),
  isha: offsetMinutes.optional(),
});
export type PrayerOffsets = z.infer<typeof PrayerOffsetsSchema>;

export const OrganizationStatusSchema = z.enum(['ACTIVE', 'SUSPENDED']);

const sheikhSchema = z.object({
  firstName: requiredName,
  fatherName: requiredName,
  familyName: requiredName,
  phone: e164Phone,
});

/**
 * WF-01, both deploy modes. Slug is generated by the server.
 * `memberLimit` is the hosted plan cap; self-host omits it.
 */
export const SetupOrganizationSchema = z.object({
  name: requiredName,
  timezone: ianaTimeZone,
  latitude,
  longitude,
  prayerMethod: PrayerMethodSchema,
  locale: LocaleSchema,
  sheikh: sheikhSchema,
  memberLimit: z.number().int().positive().optional(),
});
export type SetupOrganizationInput = z.infer<typeof SetupOrganizationSchema>;

export const SetupStatusSchema = z.object({
  setupRequired: z.boolean(),
});
export type SetupStatus = z.infer<typeof SetupStatusSchema>;

/** The only organization response that contains a secret. Do not log it. */
export const SetupOrganizationResponseSchema = z.object({
  organizationId: uuid,
  sheikhMemberId: uuid,
  setupCode,
  setupCodeExpiresAt: isoDateTime,
});
export type SetupOrganizationResponse = z.infer<typeof SetupOrganizationResponseSchema>;

export const OrganizationResponseSchema = z.object({
  id: uuid,
  name: z.string(),
  slug: z.string(),
  status: OrganizationStatusSchema,
  timezone: z.string(),
  latitude,
  longitude,
  prayerMethod: PrayerMethodSchema,
  prayerOffsets: PrayerOffsetsSchema,
  locale: LocaleSchema,
  pointsEnabled: z.boolean(),
  memberLimit: z.number().int().positive().nullable(),
  createdAt: isoDateTime,
  updatedAt: isoDateTime,
});
export type OrganizationResponse = z.infer<typeof OrganizationResponseSchema>;

export const UpdateOrganizationSchema = z
  .object({
    name: requiredName.optional(),
    timezone: ianaTimeZone.optional(),
    latitude: latitude.optional(),
    longitude: longitude.optional(),
    prayerMethod: PrayerMethodSchema.optional(),
    prayerOffsets: PrayerOffsetsSchema.optional(),
    locale: LocaleSchema.optional(),
    pointsEnabled: z.boolean().optional(),
  })
  .refine((value) => Object.keys(value).length > 0, {
    message: 'At least one field is required',
  });
export type UpdateOrganizationInput = z.infer<typeof UpdateOrganizationSchema>;